//WILAYAH
export const SET_LIST_PROVINSI = 'SET_LIST_PROVINSI';
export const SET_LIST_KABUPATEN = 'SET_LIST_KABUPATEN';
export const SET_LIST_KECAMATAN = 'SET_LIST_KECAMATAN';
export const SET_LIST_KELURAHAN = 'SET_LIST_KELURAHAN';
export const SET_LIST_WILAYAH_LOADING = 'SET_LIST_WILAYAH_LOADING';
export const SET_LIST_WILAYAH_ERROR = 'SET_LIST_WILAYAH_ERROR';
